name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.4.6']
        
    steps:
    - uses: actions/checkout@v3

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}


    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: './go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
